// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mjmwqgtvzwswtfaqwblp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1qbXdxZ3R2endzd3RmYXF3YmxwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5MjA4NzEsImV4cCI6MjA2MzQ5Njg3MX0.hT-0FP352cpP131FfddshzRVlTsepL_-YzMsn3Ljbbc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);